### ISSUE TITLE
font-size of titles

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#92]
Je trouve que c'est un peu la pagaille dans la mixin title dans `_mixin.scss`

```scss
//Title mixins
@mixin title($size: md) {
	font-weight: 700;
	line-height: $heading-line-height;
	font-family: $customfont-2;

	.fonts-loading & {
		font-family: $font-sansserif;
	}

	@if $size == XXL {
		font-size: 40px;

		@include breakpoints(sm) {
			font-size: 40px*1.5;
		}
	}
	@if $size == XL {
		font-size: 36px;

		@include breakpoints(sm) {
			font-size: 36px*1.5;
		}
	}
	@if $size == L {
		font-size: 32px;

		@include breakpoints(sm) {
			font-size: 32px*1.5;
		}
	}
	@if $size == M {
		font-size: 28px;

		@include breakpoints(sm) {
			font-size: 28px*1.5;
		}
	}
	@if $size == S {
		font-size: 24px;

		@include breakpoints(sm) {
			font-size: 24px*1.5;
		}
	}
	@if $size == XS {
		font-size: 20px;

		@include breakpoints(sm) {
			font-size: 20*1.5;
		}
	}
}
```

Je trouve que ça ne donne pas un résultat satisfaisant en terme de hiérarchisation et il manque le "px" pour le XS en breakpoints sm. Il faudrait je pense trouve un système plus smart pour cela.
